---
- hosts: "appsrv"
  name: python gunicorn deployment
   - name: Copy pyconf files 
     copy:
        src: "envsetp.sh"
        dest: "/home/ec2-user/envsetp.sh"
  - name: install python venv 
    shell: "chmod +x envsetp.sh; ./envsetp.sh"
