---
- hosts: "appsrv"
  name: python gunicorn deployment
  tasks:
  - name: Copy pyconf files 
    copy:
        src: "envsetp.sh"
        dest: "/home/ec2-user/envsetp.sh"
  - name: Create  pyvenv
    shell: "chmod +x envsetp.sh; ./envsetp.sh"
